language: go
sudo: required
services:
  - docker
go:
  - stable
before_install:
  - go get -u github.com/mattn/goveralls
  - docker pull linuxserver/rutorrent
  - docker run -d --name=rutorrent -v $HOME/data:/config -v $HOME/downloads:/downloads -e PGID=1000 -e PUID=1000 -p 80:80 -p 5000:5000 -p 51413:51413 -p 6881:6881/udp linuxserver/rutorrent
  - sleep 5
  - docker ps -a
  - docker logs rutorrent
script:
  - go vet ./...
  - goveralls -race -v -show -service=travis-ci
